In [5]:
#импорт библиотеки
import numpy as np

In [7]:
#массив из десяти нулей
array=np.zeros(10)
print("10 nuley:") 
print(array)

10 nuley:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#массив десять единиц
array=np.ones(10)
print("10 edinic")
print(array)

10 edinic
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
#массив десять пятерок
array=np.ones(10)*5
print("10 pyaterok")
print(array)

10 pyaterok
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
#массив целых чисел 10-50
array=np.arange(10,51)
print("ot 10 do 50")
print(array)

ot 10 do 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [11]:
#массив чётных чисел 10-50
array=np.arange(10,51,2)
print("ot 10 do 50")
print(array)

ot 10 do 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [13]:
#матрица 3x3 0-8
matric = np.arange(0,9).reshape(3,3)
print(matric)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#единичная матрица 3x3
matric = np.eye(3)
print(matric)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#генерация 0-1
rand = np.random.rand(1)
print("ot 0 do 1")
print(rand)

ot 0 do 1
[0.02596044]


In [16]:
#генерация массива 25 чисел
rand = np.random.rand(25)
print("25 random numbers:")
print(rand)

25 random numbers:
[0.15300081 0.23971511 0.85929748 0.27044904 0.2224729  0.39261769
 0.33468599 0.52135212 0.51794025 0.63132339 0.58386009 0.79273764
 0.45805644 0.51546689 0.42077419 0.55159499 0.00353842 0.96453046
 0.31485343 0.53867047 0.59753722 0.49919825 0.95499982 0.42181551
 0.37408733]


In [17]:
#создать матрицу
mat = np.arange(0.01,1.01,0.01).reshape(10,10)
print(mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [18]:
#стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
#вернуть матрицу из стартовой
print('array=', mat[2:,1:])

array= [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [20]:
#вернуть значение 20
dv = mat[mat == 20]
print(dv)

[20]


In [27]:
#воспроизвести вывод
print('array=', mat[0:3,1].reshape(3,1))


array= [[ 2]
 [ 7]
 [12]]


In [28]:
#воспроизвести вывод
print('array=', mat[4:])

array= [[21 22 23 24 25]]


In [29]:
#воспроизвести вывод
print('array=', mat[3:])

array= [[16 17 18 19 20]
 [21 22 23 24 25]]


In [24]:
#сумма всех значений
print(mat.sum())

325


In [25]:
#стандартное отклонение
print(mat.std())

7.211102550927978


In [30]:
#сумма значений в колонках
print(mat.sum(axis=0))

[55 60 65 70 75]
